apiVersion: v1
kind: Service
metadata:
  name: <cluster-name>-pv-pvc-creator
  namespace: default
spec:
  type: NodePort
  selector:
    app: pv-pvc-creator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-pvc-creator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pv-pvc-creator
  template:
    metadata:
      labels:
        app: pv-pvc-creator
    spec:
      containers:
      - name: pv-pvc-creator
        image: wilsonduan10/cross-persistence:latest
        ports:
        - containerPort: 8080
        env:
        - name: NFS_SERVER
          value: "10.0.0.111"  # Update with your NFS server IP or set dynamically